#pragma once

#define _WINSOCK_DEPRECATED_NO_WARNINGS
#include <WinSock2.h>

#define RMS_IOCTL_CONNECT \
		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x500, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define RMS_IOCTL_DISCONNECT \
		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x501, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define RMS_IOCTL_SEND \
		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x502, METHOD_IN_DIRECT, FILE_ANY_ACCESS)

#define RMS_IOCTL_RECV \
		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x503, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define RMS_IOCTL_CONNECTED \
		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x504, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define RMS_IOCTL_RECEIVED \
		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x505, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

//typedef struct _RMS_CONNECT_INPUT {
//	SOCKADDR_IN RemoteAddress;
//} RMS_CONNECT_INPUT, *PRMS_CONNECT_INPUT;
//
//typedef struct _RMS_BUFFER_INPUT {
//	SIZE_T BufferLength;
//} RMS_BUFFER_IO, * PRMS_BUFFER_IO;
//
//typedef struct _RMS_STATUS_OUTPUT {
//	CHAR Buffer[];
//} RMS_STATUS_OUTPUT, *PRMS_STATUS_OUTPUT;
